# TODO: include api, elastic, logstash, apm
version: '3.7'
services:
  trading-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    environment:
      PIPELINE: prod
    restart: on-failure
    
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
